// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgvx3FI5A-4bhj6vsev4tpA8pQiYSXAfU',
    appId: '1:600034946788:web:4fd4a059384e2716a686f1',
    messagingSenderId: '600034946788',
    projectId: 'pdf-scanner-85841',
    authDomain: 'pdf-scanner-85841.firebaseapp.com',
    storageBucket: 'pdf-scanner-85841.firebasestorage.app',
    measurementId: 'G-35E0H8GPMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJM5G7I6K5dTk5oOld0BEEEiH_eDjCRUA',
    appId: '1:600034946788:android:aea07d05cb421893a686f1',
    messagingSenderId: '600034946788',
    projectId: 'pdf-scanner-85841',
    storageBucket: 'pdf-scanner-85841.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKqhYj5iH04NIx_2Ev5C0gy7edpMW6FPc',
    appId: '1:600034946788:ios:dd180a6a3660d53ea686f1',
    messagingSenderId: '600034946788',
    projectId: 'pdf-scanner-85841',
    storageBucket: 'pdf-scanner-85841.firebasestorage.app',
    iosBundleId: 'com.example.pdfScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgvx3FI5A-4bhj6vsev4tpA8pQiYSXAfU',
    appId: '1:600034946788:web:a6ff1f19bf6753bfa686f1',
    messagingSenderId: '600034946788',
    projectId: 'pdf-scanner-85841',
    authDomain: 'pdf-scanner-85841.firebaseapp.com',
    storageBucket: 'pdf-scanner-85841.firebasestorage.app',
    measurementId: 'G-YFTRPNJRC5',
  );
}
